config/routes.rb
Rails.application.routes.draw do
 	root 	'sessions#home'
 	get 	'login' => 'sessions#new'
 	post 	'login' => 'sessions#create'
 	delete 	'logout' => 'sessions#destroy'
	resources :users
	resources :posts, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	attr_accessor :remember_token, :remember_digest
	before_create :create_remember_token
	has_many :posts

	has_secure_password
	validates :name, presence: true, length: {maximum: 50}
	validates :password, presence: true, length: {minimum: 6}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, 
					length: {maximum: 255},
					uniqueness: {case_sesitive: false},
					format: {with: VALID_EMAIL_REGEX}

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def remember
		self.remember_token = User.new_token
		self.remember_digest = Digest::SHA1.hexdigest(remember_token.to_s)
		update_attribute(:remember_digest, self.remember_digest)
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	def authenticated?(remember_token)
		return false if remember_digest.nil?
		#Bcrypt::Password.new(remember_digest).is_password?(remember_token)
		remember_digest == Digest::SHA1.hexdigest(remember_token.to_s)
	end

	def create_remember_token
		self.remember_token = User.new_token
		self.remember_digest = Digest::SHA1.hexdigest(self.remember_token.to_s)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :require_login, only: [:new, :create]

	def new
		@post = Post.new
	end
	def create
		@post = Post.new(:title => params[:post][:title], :body => params[:post][:body], :user => current_user)
		@post.save
		redirect_to posts_path
	end
	def index
		@posts = Post.all
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def home
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in(user)
  		remember user
  		redirect_to posts_path
  	else
  		flash.now[:danger] = 'Invalid email/password combination'
  		render 'new'
  	end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def logged_in?
		!current_user.nil?
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent.signed[:remember_token] = user.remember_token
	end

	def current_user
		if(user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div align="right">
	<%= link_to "All Posts", posts_path %>
	<% if logged_in? %>
		<%= link_to "New Post", new_post_path %>		
		<%= link_to "Log out", logout_path, method: "delete" %>
	<% else %>
		<%= link_to "Log in", login_path %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>P306MembersOnly</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/posts/index.html.erb
<center>
<h1>Submited secrets</h1>

<table style = "border: 1px solid black;">
  <tr>
    <th>Title</th>
    <th colspan="3">Text</th>
    <th>Author</th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td colspan="3"><%= post.body %></td>
      <% if logged_in? %>
      	<td><%= post.user.name %></td>
      <% else %>
      	<td>Anonymous</td>
      <% end %>
    </tr>
  <% end %>
</table>
</center>

app/views/posts/new.html.erb
<div align = "center">    
    <%= form_for @post, :url => posts_path do |f| %>
      <%= f.label :title, "    Title" %>
      <%= f.text_field :title %>
      <br>
      <%= f.label :body, "Your post" %>
      <%= f.text_area(:body, size: "30x10") %>
      <br>
      <%= f.submit "Submit" %>
    <% end %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
this users#show